//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace mojoPortal.Features.UI
{


	public partial class CommentsModule
	{

		/// <summary>
		/// pnlOuterWrap control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::mojoPortal.Web.UI.OuterWrapperPanel pnlOuterWrap;

		/// <summary>
		/// pnlInnerWrap control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::mojoPortal.Web.UI.InnerWrapperPanel pnlInnerWrap;

		/// <summary>
		/// TitleControl control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::mojoPortal.Web.UI.ModuleTitleControl TitleControl;

		/// <summary>
		/// pnlOuterBody control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::mojoPortal.Web.UI.OuterBodyPanel pnlOuterBody;

		/// <summary>
		/// pnlInnerBody control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::mojoPortal.Web.UI.InnerBodyPanel pnlInnerBody;

		/// <summary>
		/// InternalCommentSystem control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::mojoPortal.Web.UI.CommentsWidget InternalCommentSystem;

		/// <summary>
		/// divCleared control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::mojoPortal.Web.UI.EmptyPanel divCleared;
	}
}
