//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace mojoPortal.Web.AdminUI
{


	public partial class ContentTemplatesPage
	{

		/// <summary>
		/// pnlAdminCrumbs control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::mojoPortal.Web.UI.AdminCrumbContainer pnlAdminCrumbs;

		/// <summary>
		/// lnkAdminMenu control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkAdminMenu;

		/// <summary>
		/// litLinkSeparator1 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::mojoPortal.Web.UI.AdminCrumbSeparator litLinkSeparator1;

		/// <summary>
		/// lnkThisPage control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkThisPage;

		/// <summary>
		/// pnlOuterWrap control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::mojoPortal.Web.UI.OuterWrapperPanel pnlOuterWrap;

		/// <summary>
		/// pnlInnerWrap control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::mojoPortal.Web.UI.InnerWrapperPanel pnlInnerWrap;

		/// <summary>
		/// heading control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::mojoPortal.Web.UI.HeadingControl heading;

		/// <summary>
		/// pnlOuterBody control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::mojoPortal.Web.UI.OuterBodyPanel pnlOuterBody;

		/// <summary>
		/// pnlInnerBody control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::mojoPortal.Web.UI.InnerBodyPanel pnlInnerBody;

		/// <summary>
		/// lnkAddNewTop control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkAddNewTop;

		/// <summary>
		/// lnkExportTop control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkExportTop;

		/// <summary>
		/// pgrTop control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::mojoPortal.Web.UI.mojoCutePager pgrTop;

		/// <summary>
		/// rptTemplates control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Repeater rptTemplates;

		/// <summary>
		/// lnkAddNewBottom control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkAddNewBottom;

		/// <summary>
		/// lnkExportBottom control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkExportBottom;

		/// <summary>
		/// pgrBottom control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::mojoPortal.Web.UI.mojoCutePager pgrBottom;

		/// <summary>
		/// divCleared control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::mojoPortal.Web.UI.EmptyPanel divCleared;
	}
}
