//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace mojoPortal.Web.AdminUI
{


	public partial class ContentCatalogPage
	{

		/// <summary>
		/// pnlAdminCrumbs control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::mojoPortal.Web.UI.AdminCrumbContainer pnlAdminCrumbs;

		/// <summary>
		/// lnkAdminMenu control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkAdminMenu;

		/// <summary>
		/// litLinkSeparator1 control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::mojoPortal.Web.UI.AdminCrumbSeparator litLinkSeparator1;

		/// <summary>
		/// lnkContentManager control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HyperLink lnkContentManager;

		/// <summary>
		/// pnlOuterWrap control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::mojoPortal.Web.UI.OuterWrapperPanel pnlOuterWrap;

		/// <summary>
		/// pnlInnerWrap control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::mojoPortal.Web.UI.InnerWrapperPanel pnlInnerWrap;

		/// <summary>
		/// heading control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::mojoPortal.Web.UI.HeadingControl heading;

		/// <summary>
		/// pnlOuterBody control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::mojoPortal.Web.UI.OuterBodyPanel pnlOuterBody;

		/// <summary>
		/// pnlInnerBody control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::mojoPortal.Web.UI.InnerBodyPanel pnlInnerBody;

		/// <summary>
		/// pnlFind control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel pnlFind;

		/// <summary>
		/// lblTitleFilter control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::mojoPortal.Web.Controls.SiteLabel lblTitleFilter;

		/// <summary>
		/// txtTitleFilter control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.TextBox txtTitleFilter;

		/// <summary>
		/// ddModuleType control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.DropDownList ddModuleType;

		/// <summary>
		/// btnFind control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::mojoPortal.Web.UI.mojoButton btnFind;

		/// <summary>
		/// grdContent control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::mojoPortal.Web.Controls.mojoGridView grdContent;

		/// <summary>
		/// pgrContent control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::mojoPortal.Web.UI.mojoCutePager pgrContent;
	}
}
