//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProfileResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProfileResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ProfileResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIM.
        /// </summary>
        internal static string AIMLabel {
            get {
                return ResourceManager.GetString("AIMLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brief Author Biography.
        /// </summary>
        internal static string AuthorBio {
            get {
                return ResourceManager.GetString("AuthorBio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string CountryLabel {
            get {
                return ResourceManager.GetString("CountryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        internal static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string DateOfBirthLabel {
            get {
                return ResourceManager.GetString("DateOfBirthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string GenderFemaleLabel {
            get {
                return ResourceManager.GetString("GenderFemaleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string GenderLabel {
            get {
                return ResourceManager.GetString("GenderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string GenderMaleLabel {
            get {
                return ResourceManager.GetString("GenderMaleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GenderUnselectedLabel {
            get {
                return ResourceManager.GetString("GenderUnselectedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICQ.
        /// </summary>
        internal static string ICQLabel {
            get {
                return ResourceManager.GetString("ICQLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interests.
        /// </summary>
        internal static string InterestsLabel {
            get {
                return ResourceManager.GetString("InterestsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSN.
        /// </summary>
        internal static string MSNLabel {
            get {
                return ResourceManager.GetString("MSNLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        internal static string OccupationLabel {
            get {
                return ResourceManager.GetString("OccupationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        internal static string ProfileRequiredItemFormat {
            get {
                return ResourceManager.GetString("ProfileRequiredItemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string RequiredLabel {
            get {
                return ResourceManager.GetString("RequiredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        internal static string SignatureLabel {
            get {
                return ResourceManager.GetString("SignatureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string StateLabel {
            get {
                return ResourceManager.GetString("StateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Zone.
        /// </summary>
        internal static string TimeOffsetLabel {
            get {
                return ResourceManager.GetString("TimeOffsetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT + 4.00) Abu Dhabi, Muscat, Baku, Tbilisi.
        /// </summary>
        internal static string TimeZoneLabelAbuDhabiMuscatBakuTbilisi {
            get {
                return ResourceManager.GetString("TimeZoneLabelAbuDhabiMuscatBakuTbilisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT + 9.50) Adelaide, Darwin.
        /// </summary>
        internal static string TimeZoneLabelAdelaideDarwin {
            get {
                return ResourceManager.GetString("TimeZoneLabelAdelaideDarwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT - 9.00) Alaska.
        /// </summary>
        internal static string TimeZoneLabelAlaska {
            get {
                return ResourceManager.GetString("TimeZoneLabelAlaska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT + 6.00) Almaty, Dhaka, Colombo.
        /// </summary>
        internal static string TimeZoneLabelAlmatyDhakaColombo {
            get {
                return ResourceManager.GetString("TimeZoneLabelAlmatyDhakaColombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT - 4.00) Atlantic Time (Canada), Caracas, La Paz.
        /// </summary>
        internal static string TimeZoneLabelAtlantic {
            get {
                return ResourceManager.GetString("TimeZoneLabelAtlantic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT + 12.00) Auckland, Wellington, Fiji, Kamchatka, Marshall Island.
        /// </summary>
        internal static string TimeZoneLabelAucklandWellingtonFijiKamchatkaMarshallIsland {
            get {
                return ResourceManager.GetString("TimeZoneLabelAucklandWellingtonFijiKamchatkaMarshallIsland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT - 1.00) Azores, Cape Verde Islands.
        /// </summary>
        internal static string TimeZoneLabelAzoresCapeVerdeIslands {
            get {
                return ResourceManager.GetString("TimeZoneLabelAzoresCapeVerdeIslands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT + 3.00) Baghdad, Kuwait, Riyadh, Moscow, St. Petersburg, Volgograd, Nairobi.
        /// </summary>
        internal static string TimeZoneLabelBaghdadKuwaitRiyadhMoscowStPetersburgVolgogradNairobi {
            get {
                return ResourceManager.GetString("TimeZoneLabelBaghdadKuwaitRiyadhMoscowStPetersburgVolgogradNairobi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT + 7.00) Bangkok, Hanoi, Jakarta.
        /// </summary>
        internal static string TimeZoneLabelBangkokHanoiJakarta {
            get {
                return ResourceManager.GetString("TimeZoneLabelBangkokHanoiJakarta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT + 8.00) Beijing, Perth, Singapore, Hong Kong, Chongqing, Urumqi, Taipei.
        /// </summary>
        internal static string TimeZoneLabelBeijingPerthSingaporeHongKongChongqingUrumqiTaipei {
            get {
                return ResourceManager.GetString("TimeZoneLabelBeijingPerthSingaporeHongKongChongqingUrumqiTaipei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT + 5.50) Bombay, Calcutta, Madras, New Delhi.
        /// </summary>
        internal static string TimeZoneLabelBombayCalcuttaMadrasNewDelhi {
            get {
                return ResourceManager.GetString("TimeZoneLabelBombayCalcuttaMadrasNewDelhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT - 3.00) Brazil, Buenos Aires, Georgetown.
        /// </summary>
        internal static string TimeZoneLabelBrazilBuenosAiresGeorgetown {
            get {
                return ResourceManager.GetString("TimeZoneLabelBrazilBuenosAiresGeorgetown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT - 6.00) Central Time (US &amp; Canada), Mexico City.
        /// </summary>
        internal static string TimeZoneLabelCentral {
            get {
                return ResourceManager.GetString("TimeZoneLabelCentral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT + 1.00) CET(Central Europe Time), Brussels, Copenhagen, Madrid, Paris.
        /// </summary>
        internal static string TimeZoneLabelCentralEurope {
            get {
                return ResourceManager.GetString("TimeZoneLabelCentralEurope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT + 10.00) EAST(East Australian Standard), Guam, Papua New Guinea, Vladivostok.
        /// </summary>
        internal static string TimeZoneLabelEASTEastAustralianStandardGuamPapuaNewGuineaVladivostok {
            get {
                return ResourceManager.GetString("TimeZoneLabelEASTEastAustralianStandardGuamPapuaNewGuineaVladivostok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT - 5.00) Eastern Time (US &amp; Canada), Bogota, Lima, Quito.
        /// </summary>
        internal static string TimeZoneLabelEastern {
            get {
                return ResourceManager.GetString("TimeZoneLabelEastern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT + 2.00) EET(Eastern Europe Time), Kaliningrad, South Africa.
        /// </summary>
        internal static string TimeZoneLabelEasternEurope {
            get {
                return ResourceManager.GetString("TimeZoneLabelEasternEurope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT + 5.00) Ekaterinburg, Islamabad, Karachi, Tashkent.
        /// </summary>
        internal static string TimeZoneLabelEkaterinburgIslamabadKarachiTashkent {
            get {
                return ResourceManager.GetString("TimeZoneLabelEkaterinburgIslamabadKarachiTashkent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT - 12.00) Eniwetok, Kwajalein.
        /// </summary>
        internal static string TimeZoneLabelEniwetokKwajalein {
            get {
                return ResourceManager.GetString("TimeZoneLabelEniwetokKwajalein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT) Western Europe Time, London, Lisbon, Casablanca, Monrovia.
        /// </summary>
        internal static string TimeZoneLabelGMT {
            get {
                return ResourceManager.GetString("TimeZoneLabelGMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT - 10.00) Hawaii.
        /// </summary>
        internal static string TimeZoneLabelHawaii {
            get {
                return ResourceManager.GetString("TimeZoneLabelHawaii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT + 4.50) Kabul.
        /// </summary>
        internal static string TimeZoneLabelKabul {
            get {
                return ResourceManager.GetString("TimeZoneLabelKabul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT + 11.00) Magadan, Solomon Islands, New Caledonia.
        /// </summary>
        internal static string TimeZoneLabelMagadanSolomonIslandsNewCaledonia {
            get {
                return ResourceManager.GetString("TimeZoneLabelMagadanSolomonIslandsNewCaledonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT - 2.00) Mid-Atlantic.
        /// </summary>
        internal static string TimeZoneLabelMidAtlantic {
            get {
                return ResourceManager.GetString("TimeZoneLabelMidAtlantic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT - 11.00) Midway Island, Samoa .
        /// </summary>
        internal static string TimeZoneLabelMidwayIslandSamoa {
            get {
                return ResourceManager.GetString("TimeZoneLabelMidwayIslandSamoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT - 7.00) Mountain Time (US &amp; Canada) .
        /// </summary>
        internal static string TimeZoneLabelMountain {
            get {
                return ResourceManager.GetString("TimeZoneLabelMountain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT - 3.50) Newfoundland.
        /// </summary>
        internal static string TimeZoneLabelNewfoundland {
            get {
                return ResourceManager.GetString("TimeZoneLabelNewfoundland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT + 13.00) Nuku&quot;alofa.
        /// </summary>
        internal static string TimeZoneLabelNukualofa {
            get {
                return ResourceManager.GetString("TimeZoneLabelNukualofa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT - 8.00) Pacific Time (US &amp; Canada).
        /// </summary>
        internal static string TimeZoneLabelPacific {
            get {
                return ResourceManager.GetString("TimeZoneLabelPacific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT + 3.50) Tehran.
        /// </summary>
        internal static string TimeZoneLabelTehran {
            get {
                return ResourceManager.GetString("TimeZoneLabelTehran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT + 9.00) Tokyo, Seoul, Osaka, Sapporo, Yakutsk.
        /// </summary>
        internal static string TimeZoneLabelTokyoSeoulOsakaSapporoYakutsk {
            get {
                return ResourceManager.GetString("TimeZoneLabelTokyoSeoulOsakaSapporoYakutsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Site URL.
        /// </summary>
        internal static string WebSiteUrlLabel {
            get {
                return ResourceManager.GetString("WebSiteUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must be an url starting with http:// or https://.
        /// </summary>
        internal static string WebSiteUrlRegexWarning {
            get {
                return ResourceManager.GetString("WebSiteUrlRegexWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some information is not shown because you are not signed into this site..
        /// </summary>
        internal static string WouldSeeMoreIfAuthenticatedMessage {
            get {
                return ResourceManager.GetString("WouldSeeMoreIfAuthenticatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yahoo.
        /// </summary>
        internal static string YahooLabel {
            get {
                return ResourceManager.GetString("YahooLabel", resourceCulture);
            }
        }
    }
}
