//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MyPageResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration Menu.
        /// </summary>
        internal static string AdminMenuLink {
            get {
                return ResourceManager.GetString("AdminMenuLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Part Installation.
        /// </summary>
        internal static string AdminMenuWebPartAdminLink {
            get {
                return ResourceManager.GetString("AdminMenuWebPartAdminLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Tools.
        /// </summary>
        internal static string AdvancedToolsLink {
            get {
                return ResourceManager.GetString("AdvancedToolsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A customizable personal portal page for members of {0}..
        /// </summary>
        internal static string MetaDescriptionMyPageFormat {
            get {
                return ResourceManager.GetString("MetaDescriptionMyPageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string ModuleSettingsNoIconLabel {
            get {
                return ResourceManager.GetString("ModuleSettingsNoIconLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Content.
        /// </summary>
        internal static string mojoUserCatalogPartTitle {
            get {
                return ResourceManager.GetString("mojoUserCatalogPartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Content.
        /// </summary>
        internal static string MyPageAddContentLabel {
            get {
                return ResourceManager.GetString("MyPageAddContentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you sign in you can customize this page..
        /// </summary>
        internal static string MyPageAnonymousMessage {
            get {
                return ResourceManager.GetString("MyPageAnonymousMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string MyPageCancelNewPageButton {
            get {
                return ResourceManager.GetString("MyPageCancelNewPageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string MyPageCancelRenamePageButton {
            get {
                return ResourceManager.GetString("MyPageCancelRenamePageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string MyPageCenterLabel {
            get {
                return ResourceManager.GetString("MyPageCenterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Name.
        /// </summary>
        internal static string MyPageChangeNameText {
            get {
                return ResourceManager.GetString("MyPageChangeNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string MyPageDefaultUserPageName {
            get {
                return ResourceManager.GetString("MyPageDefaultUserPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this content?.
        /// </summary>
        internal static string MyPageDeleteWarning {
            get {
                return ResourceManager.GetString("MyPageDeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Side.
        /// </summary>
        internal static string MyPageLeftSideLabel {
            get {
                return ResourceManager.GetString("MyPageLeftSideLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyPage.
        /// </summary>
        internal static string MyPageLink {
            get {
                return ResourceManager.GetString("MyPageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Left.
        /// </summary>
        internal static string MyPageMoveLeftText {
            get {
                return ResourceManager.GetString("MyPageMoveLeftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Right.
        /// </summary>
        internal static string MyPageMoveRightText {
            get {
                return ResourceManager.GetString("MyPageMoveRightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Page.
        /// </summary>
        internal static string MyPageNewPageButton {
            get {
                return ResourceManager.GetString("MyPageNewPageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string MyPageRemoveText {
            get {
                return ResourceManager.GetString("MyPageRemoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Name.
        /// </summary>
        internal static string MyPageRenamePageButton {
            get {
                return ResourceManager.GetString("MyPageRenamePageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Side.
        /// </summary>
        internal static string MyPageRightSideLabel {
            get {
                return ResourceManager.GetString("MyPageRightSideLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyPage Skin.
        /// </summary>
        internal static string MyPageSkinLabel {
            get {
                return ResourceManager.GetString("MyPageSkinLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Scope.
        /// </summary>
        internal static string MyPageToggleScopeLabel {
            get {
                return ResourceManager.GetString("MyPageToggleScopeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds content to the selected column.
        /// </summary>
        internal static string WebPartAddVerbDescription {
            get {
                return ResourceManager.GetString("WebPartAddVerbDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string WebPartAddVerbText {
            get {
                return ResourceManager.GetString("WebPartAddVerbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All WebParts.
        /// </summary>
        internal static string WebPartAdminAllWebParts {
            get {
                return ResourceManager.GetString("WebPartAdminAllWebParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install....
        /// </summary>
        internal static string WebPartAdminEditButton {
            get {
                return ResourceManager.GetString("WebPartAdminEditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this site appears to be running in a Medium Trust security environment. Loading 3rd party dlls is not supported under Medium Trust. You can still use all of the built in Features as WebParts, but you cannot load WebParts directly from the assemblies in this environment. For more information see http://www.mojoportal.com/mediumtrust.aspx.
        /// </summary>
        internal static string WebPartAdminMediumTrustMessage {
            get {
                return ResourceManager.GetString("WebPartAdminMediumTrustMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected WebParts.
        /// </summary>
        internal static string WebPartAdminSelectedWebParts {
            get {
                return ResourceManager.GetString("WebPartAdminSelectedWebParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string WebPartAdminUpdateButton {
            get {
                return ResourceManager.GetString("WebPartAdminUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Available WebParts are Currently Installed. To add new WebParts, drop the assembly in the bin folder..
        /// </summary>
        internal static string WebPartAllInstalledMessage {
            get {
                return ResourceManager.GetString("WebPartAllInstalledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Multiple Instances on MyPage?.
        /// </summary>
        internal static string WebPartAllowMultipleInstancesOnMyPageLabel {
            get {
                return ResourceManager.GetString("WebPartAllowMultipleInstancesOnMyPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string WebPartAppearanceEditorTitle {
            get {
                return ResourceManager.GetString("WebPartAppearanceEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Name.
        /// </summary>
        internal static string WebPartAssemblyNameLabel {
            get {
                return ResourceManager.GetString("WebPartAssemblyNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available for Content System.
        /// </summary>
        internal static string WebPartAvailableForContentSystemLabel {
            get {
                return ResourceManager.GetString("WebPartAvailableForContentSystemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available for MyPage?.
        /// </summary>
        internal static string WebPartAvailableForMyPageLabel {
            get {
                return ResourceManager.GetString("WebPartAvailableForMyPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebParts Available For Installation.
        /// </summary>
        internal static string WebPartAvailableNameLabel {
            get {
                return ResourceManager.GetString("WebPartAvailableNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        internal static string WebPartBehaviorEditorTitle {
            get {
                return ResourceManager.GetString("WebPartBehaviorEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more....
        /// </summary>
        internal static string WebPartCatalogMoreLink {
            get {
                return ResourceManager.GetString("WebPartCatalogMoreLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Name.
        /// </summary>
        internal static string WebPartClassNameLabel {
            get {
                return ResourceManager.GetString("WebPartClassNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close this content.
        /// </summary>
        internal static string WebPartCloseVerbDescription {
            get {
                return ResourceManager.GetString("WebPartCloseVerbDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string WebPartCloseVerbText {
            get {
                return ResourceManager.GetString("WebPartCloseVerbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this content.
        /// </summary>
        internal static string WebPartDeleteVerbDescription {
            get {
                return ResourceManager.GetString("WebPartDeleteVerbDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string WebPartDeleteVerbText {
            get {
                return ResourceManager.GetString("WebPartDeleteVerbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string WebPartDescriptionLabel {
            get {
                return ResourceManager.GetString("WebPartDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string WebPartEditCancelButton {
            get {
                return ResourceManager.GetString("WebPartEditCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string WebPartEditDeleteButton {
            get {
                return ResourceManager.GetString("WebPartEditDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this WebPart?.
        /// </summary>
        internal static string WebPartEditDeleteWarning {
            get {
                return ResourceManager.GetString("WebPartEditDeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit WebPart.
        /// </summary>
        internal static string WebPartEditLabel {
            get {
                return ResourceManager.GetString("WebPartEditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies your changes.
        /// </summary>
        internal static string WebPartEditorApplyVerbDescription {
            get {
                return ResourceManager.GetString("WebPartEditorApplyVerbDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string WebPartEditorApplyVerbText {
            get {
                return ResourceManager.GetString("WebPartEditorApplyVerbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancels changes and closes the editor..
        /// </summary>
        internal static string WebPartEditorCancelVerbDescription {
            get {
                return ResourceManager.GetString("WebPartEditorCancelVerbDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string WebPartEditorCancelVerbText {
            get {
                return ResourceManager.GetString("WebPartEditorCancelVerbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes the editor.
        /// </summary>
        internal static string WebPartEditorHeaderCloseVerbDescription {
            get {
                return ResourceManager.GetString("WebPartEditorHeaderCloseVerbDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string WebPartEditorHeaderCloseVerbText {
            get {
                return ResourceManager.GetString("WebPartEditorHeaderCloseVerbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Part Editor.
        /// </summary>
        internal static string WebPartEditorHeaderText {
            get {
                return ResourceManager.GetString("WebPartEditorHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify the properties of the Web Part, then click OK or Apply to apply your changes. Some Web Parts have no editable properties..
        /// </summary>
        internal static string WebPartEditorInstructionsText {
            get {
                return ResourceManager.GetString("WebPartEditorInstructionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies changes and closes the editor..
        /// </summary>
        internal static string WebPartEditorOKVerbDescription {
            get {
                return ResourceManager.GetString("WebPartEditorOKVerbDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string WebPartEditorOKVerbText {
            get {
                return ResourceManager.GetString("WebPartEditorOKVerbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string WebPartEditUpdateButton {
            get {
                return ResourceManager.GetString("WebPartEditUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string WebPartEditVerbDescription {
            get {
                return ResourceManager.GetString("WebPartEditVerbDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string WebPartEditVerbText {
            get {
                return ResourceManager.GetString("WebPartEditVerbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry no content is currently available.
        /// </summary>
        internal static string WebPartEmptyCatalogZoneText {
            get {
                return ResourceManager.GetString("WebPartEmptyCatalogZoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can drag content here from other columns or click the green plus to add content..
        /// </summary>
        internal static string WebPartEmptyZoneText {
            get {
                return ResourceManager.GetString("WebPartEmptyZoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string WebPartExportVerbDescription {
            get {
                return ResourceManager.GetString("WebPartExportVerbDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string WebPartExportVerbText {
            get {
                return ResourceManager.GetString("WebPartExportVerbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Part.
        /// </summary>
        internal static string WebPartFeatureName {
            get {
                return ResourceManager.GetString("WebPartFeatureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string WebPartHelpVerbDescription {
            get {
                return ResourceManager.GetString("WebPartHelpVerbDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string WebPartHelpVerbText {
            get {
                return ResourceManager.GetString("WebPartHelpVerbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string WebPartIconLabel {
            get {
                return ResourceManager.GetString("WebPartIconLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed WebParts.
        /// </summary>
        internal static string WebPartInstalledWebPartsLabel {
            get {
                return ResourceManager.GetString("WebPartInstalledWebPartsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string WebPartLayoutEditorPartTitle {
            get {
                return ResourceManager.GetString("WebPartLayoutEditorPartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to view available content..
        /// </summary>
        internal static string WebPartManagerCatalogTooltip {
            get {
                return ResourceManager.GetString("WebPartManagerCatalogTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to close the catalog..
        /// </summary>
        internal static string WebPartManagerCloseCatalogTooltip {
            get {
                return ResourceManager.GetString("WebPartManagerCloseCatalogTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Content.
        /// </summary>
        internal static string WebPartManagerResetButton {
            get {
                return ResourceManager.GetString("WebPartManagerResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently in User Scope. Click here to toggle to Shared Scope..
        /// </summary>
        internal static string WebPartManagerToggleFromUserModeTooltip {
            get {
                return ResourceManager.GetString("WebPartManagerToggleFromUserModeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently in Shared Scope.  Click here to toggle to User Scope..
        /// </summary>
        internal static string WebPartManagerToggleToUserModeTooltip {
            get {
                return ResourceManager.GetString("WebPartManagerToggleToUserModeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize this content.
        /// </summary>
        internal static string WebPartMinimizeVerbDescription {
            get {
                return ResourceManager.GetString("WebPartMinimizeVerbDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        internal static string WebPartMinimizeVerbText {
            get {
                return ResourceManager.GetString("WebPartMinimizeVerbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Web Part.
        /// </summary>
        internal static string WebPartModuleWebPartSetting {
            get {
                return ResourceManager.GetString("WebPartModuleWebPartSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden Content.
        /// </summary>
        internal static string WebPartPageCatalogDescription {
            get {
                return ResourceManager.GetString("WebPartPageCatalogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden Content.
        /// </summary>
        internal static string WebPartPageCatalogTitle {
            get {
                return ResourceManager.GetString("WebPartPageCatalogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Part Properties.
        /// </summary>
        internal static string WebPartPropertyGridEditorTitle {
            get {
                return ResourceManager.GetString("WebPartPropertyGridEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore this content.
        /// </summary>
        internal static string WebPartRestoreVerbDescription {
            get {
                return ResourceManager.GetString("WebPartRestoreVerbDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string WebPartRestoreVerbText {
            get {
                return ResourceManager.GetString("WebPartRestoreVerbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string WebPartTitleLabel {
            get {
                return ResourceManager.GetString("WebPartTitleLabel", resourceCulture);
            }
        }
    }
}
