//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ForumResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ForumResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ForumResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add No Index Meta Tag?.
        /// </summary>
        internal static string AddNoIndexMeta {
            get {
                return ResourceManager.GetString("AddNoIndexMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe of user from forum notification completed..
        /// </summary>
        internal static string AdminUnsubscribeUserComplete {
            get {
                return ResourceManager.GetString("AdminUnsubscribeUserComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Anonymous Posts?.
        /// </summary>
        internal static string AllowAnonymousPostsLabel {
            get {
                return ResourceManager.GetString("AllowAnonymousPostsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Users To Edit Their Posts For Up To This Many Minutes.
        /// </summary>
        internal static string AllowEditingPostsLessThanMinutesOld {
            get {
                return ResourceManager.GetString("AllowEditingPostsLessThanMinutesOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Moderators to Choose Notification Option (per post).
        /// </summary>
        internal static string AllowModeratorChooseNotifyOptions {
            get {
                return ResourceManager.GetString("AllowModeratorChooseNotifyOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Un-Moderated Notification for Trusted Users?.
        /// </summary>
        internal static string AllowTrustedDirectNotify {
            get {
                return ResourceManager.GetString("AllowTrustedDirectNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait....
        /// </summary>
        internal static string ButtonDisabledPleaseWait {
            get {
                return ResourceManager.GetString("ButtonDisabledPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close this Forum to New Posts?.
        /// </summary>
        internal static string CloseForum {
            get {
                return ResourceManager.GetString("CloseForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close threads older than this many days.
        /// </summary>
        internal static string CloseThreadsOlderThanDays {
            get {
                return ResourceManager.GetString("CloseThreadsOlderThanDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to mark this post as the answer to this thread?.
        /// </summary>
        internal static string ConfirmMarkAsAnswer {
            get {
                return ResourceManager.GetString("ConfirmMarkAsAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel notification for this post by marking it as sent?.
        /// </summary>
        internal static string ConfirmMarkAsSent {
            get {
                return ResourceManager.GetString("ConfirmMarkAsSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to send this post to forum subscribers?.
        /// </summary>
        internal static string ConfirmSendNotification {
            get {
                return ResourceManager.GetString("ConfirmSendNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom CSS Class.
        /// </summary>
        internal static string CustomCssClassSetting {
            get {
                return ResourceManager.GetString("CustomCssClassSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Custom CSS Class.
        /// </summary>
        internal static string CustomCssClassSettingRegexWarning {
            get {
                return ResourceManager.GetString("CustomCssClassSettingRegexWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to First Page.
        /// </summary>
        internal static string CutePagerBackToFirstClause {
            get {
                return ResourceManager.GetString("CutePagerBackToFirstClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Page.
        /// </summary>
        internal static string CutePagerBackToPageClause {
            get {
                return ResourceManager.GetString("CutePagerBackToPageClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to Last Page.
        /// </summary>
        internal static string CutePagerGoToLastClause {
            get {
                return ResourceManager.GetString("CutePagerGoToLastClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to Page.
        /// </summary>
        internal static string CutePagerNavigateToPageText {
            get {
                return ResourceManager.GetString("CutePagerNavigateToPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next to Page.
        /// </summary>
        internal static string CutePagerNextToPageClause {
            get {
                return ResourceManager.GetString("CutePagerNextToPageClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string CutePagerOfClause {
            get {
                return ResourceManager.GetString("CutePagerOfClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string CutePagerPageClause {
            get {
                return ResourceManager.GetString("CutePagerPageClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add NOINDEX Meta To New Threads By Default?.
        /// </summary>
        internal static string DefaultAddNoIndexMeta {
            get {
                return ResourceManager.GetString("DefaultAddNoIndexMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this forum?.
        /// </summary>
        internal static string DeleteForumWarning {
            get {
                return ResourceManager.GetString("DeleteForumWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditImageAltText {
            get {
                return ResourceManager.GetString("EditImageAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this post?.
        /// </summary>
        internal static string ForumDeletePostWarning {
            get {
                return ResourceManager.GetString("ForumDeletePostWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this thread?.
        /// </summary>
        internal static string ForumDeleteThreadWarning {
            get {
                return ResourceManager.GetString("ForumDeleteThreadWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ForumEditCancelButton {
            get {
                return ResourceManager.GetString("ForumEditCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string ForumEditCancelButtonAccessKey {
            get {
                return ResourceManager.GetString("ForumEditCancelButtonAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Forum.
        /// </summary>
        internal static string ForumEditCreateButton {
            get {
                return ResourceManager.GetString("ForumEditCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By:.
        /// </summary>
        internal static string ForumEditCreatedByLabel {
            get {
                return ResourceManager.GetString("ForumEditCreatedByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created:.
        /// </summary>
        internal static string ForumEditCreatedDateLabel {
            get {
                return ResourceManager.GetString("ForumEditCreatedDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this item.
        /// </summary>
        internal static string ForumEditDeleteButton {
            get {
                return ResourceManager.GetString("ForumEditDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string ForumEditDeleteButtonAccessKey {
            get {
                return ResourceManager.GetString("ForumEditDeleteButtonAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ForumEditDescriptionLabel {
            get {
                return ResourceManager.GetString("ForumEditDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Forum.
        /// </summary>
        internal static string ForumEditForumLabel {
            get {
                return ResourceManager.GetString("ForumEditForumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active?.
        /// </summary>
        internal static string ForumEditIsActiveLabel {
            get {
                return ResourceManager.GetString("ForumEditIsActiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Moderated?.
        /// </summary>
        internal static string ForumEditIsModeratedLabel {
            get {
                return ResourceManager.GetString("ForumEditIsModeratedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Forum.
        /// </summary>
        internal static string ForumEditLabel {
            get {
                return ResourceManager.GetString("ForumEditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Forum.
        /// </summary>
        internal static string ForumEditNewForumButton {
            get {
                return ResourceManager.GetString("ForumEditNewForumButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Post.
        /// </summary>
        internal static string ForumEditPostLink {
            get {
                return ResourceManager.GetString("ForumEditPostLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts Per Page:.
        /// </summary>
        internal static string ForumEditPostsPerPageLabel {
            get {
                return ResourceManager.GetString("ForumEditPostsPerPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Order:.
        /// </summary>
        internal static string ForumEditSortOrderLabel {
            get {
                return ResourceManager.GetString("ForumEditSortOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Must Enter a Subject.
        /// </summary>
        internal static string ForumEditSubjectRequiredHelp {
            get {
                return ResourceManager.GetString("ForumEditSubjectRequiredHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread Per Page:.
        /// </summary>
        internal static string ForumEditThreadsPerPageLabel {
            get {
                return ResourceManager.GetString("ForumEditThreadsPerPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string ForumEditTitleLabel {
            get {
                return ResourceManager.GetString("ForumEditTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ForumEditUpdateButton {
            get {
                return ResourceManager.GetString("ForumEditUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string ForumEditUpdateButtonAccessKey {
            get {
                return ResourceManager.GetString("ForumEditUpdateButtonAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable SPAM Blocking?.
        /// </summary>
        internal static string ForumEnableAntiSpamSetting {
            get {
                return ResourceManager.GetString("ForumEnableAntiSpamSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable RSS At Forum Level?.
        /// </summary>
        internal static string ForumEnableRSSAtForumLevel {
            get {
                return ResourceManager.GetString("ForumEnableRSSAtForumLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable RSS At Module Level?.
        /// </summary>
        internal static string ForumEnableRSSAtModuleLevel {
            get {
                return ResourceManager.GetString("ForumEnableRSSAtModuleLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable RSS At Thread Level?.
        /// </summary>
        internal static string ForumEnableRSSAtThreadLevel {
            get {
                return ResourceManager.GetString("ForumEnableRSSAtThreadLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string ForumIcon {
            get {
                return ResourceManager.GetString("ForumIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        internal static string ForumLabel {
            get {
                return ResourceManager.GetString("ForumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A discussion forum for {0}.
        /// </summary>
        internal static string ForumMetaDescriptionFormat {
            get {
                return ResourceManager.GetString("ForumMetaDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Email Subscriptions.
        /// </summary>
        internal static string ForumModuleEditSubscriptionsLabel {
            get {
                return ResourceManager.GetString("ForumModuleEditSubscriptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        internal static string ForumModuleForumLabel {
            get {
                return ResourceManager.GetString("ForumModuleForumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Posts.
        /// </summary>
        internal static string ForumModulePostCountLabel {
            get {
                return ResourceManager.GetString("ForumModulePostCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Post.
        /// </summary>
        internal static string ForumModulePostLastPostLabel {
            get {
                return ResourceManager.GetString("ForumModulePostLastPostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe?.
        /// </summary>
        internal static string ForumModuleSubscribedLabel {
            get {
                return ResourceManager.GetString("ForumModuleSubscribedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Threads.
        /// </summary>
        internal static string ForumModuleThreadCountLabel {
            get {
                return ResourceManager.GetString("ForumModuleThreadCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Posts.
        /// </summary>
        internal static string ForumMyPostsLink {
            get {
                return ResourceManager.GetString("ForumMyPostsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ForumPostEditCancelButton {
            get {
                return ResourceManager.GetString("ForumPostEditCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ForumPostEditDeleteButton {
            get {
                return ResourceManager.GetString("ForumPostEditDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message:.
        /// </summary>
        internal static string ForumPostEditMessageLabel {
            get {
                return ResourceManager.GetString("ForumPostEditMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to replies on this thread?.
        /// </summary>
        internal static string ForumPostEditNotifyLabel {
            get {
                return ResourceManager.GetString("ForumPostEditNotifyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string ForumPostEditSubjectLabel {
            get {
                return ResourceManager.GetString("ForumPostEditSubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string ForumPostEditUpdateButton {
            get {
                return ResourceManager.GetString("ForumPostEditUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string ForumPostEditUpdateButtonAccessKey {
            get {
                return ResourceManager.GetString("ForumPostEditUpdateButtonAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forums.
        /// </summary>
        internal static string ForumsFeatureName {
            get {
                return ResourceManager.GetString("ForumsFeatureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must sign in to post in the forums..
        /// </summary>
        internal static string ForumsLoginRequiredLink {
            get {
                return ResourceManager.GetString("ForumsLoginRequiredLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forums.
        /// </summary>
        internal static string ForumsSearchName {
            get {
                return ResourceManager.GetString("ForumsSearchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This table contains a list of Forums..
        /// </summary>
        internal static string ForumsTableSummary {
            get {
                return ResourceManager.GetString("ForumsTableSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum Subscriptions.
        /// </summary>
        internal static string ForumSubscriptions {
            get {
                return ResourceManager.GetString("ForumSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ForumThreadCancelButton {
            get {
                return ResourceManager.GetString("ForumThreadCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ForumThreadDeleteButton {
            get {
                return ResourceManager.GetString("ForumThreadDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        internal static string ForumThreadEditForumLabel {
            get {
                return ResourceManager.GetString("ForumThreadEditForumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Thread.
        /// </summary>
        internal static string ForumThreadEditLabel {
            get {
                return ResourceManager.GetString("ForumThreadEditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Order.
        /// </summary>
        internal static string ForumThreadEditSortOrderLabel {
            get {
                return ResourceManager.GetString("ForumThreadEditSortOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string ForumThreadEditSubjectLabel {
            get {
                return ResourceManager.GetString("ForumThreadEditSubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum Thread - {0}.
        /// </summary>
        internal static string ForumThreadMetaDescriptionFormat {
            get {
                return ResourceManager.GetString("ForumThreadMetaDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe completed!  You should not receive any more notifications for messages in the requested thread..
        /// </summary>
        internal static string ForumThreadUnsubscribeCompleted {
            get {
                return ResourceManager.GetString("ForumThreadUnsubscribeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe FAILED!  An error occurred when attempting to stop notifications for a thread.  Please contact the site administrator..
        /// </summary>
        internal static string ForumThreadUnsubscribeFailed {
            get {
                return ResourceManager.GetString("ForumThreadUnsubscribeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ForumThreadUpdateButton {
            get {
                return ResourceManager.GetString("ForumThreadUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string ForumThreadViewAuthorLabel {
            get {
                return ResourceManager.GetString("ForumThreadViewAuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages:.
        /// </summary>
        internal static string ForumThreadViewPagesLabel {
            get {
                return ResourceManager.GetString("ForumThreadViewPagesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        internal static string ForumThreadViewReplyLabel {
            get {
                return ResourceManager.GetString("ForumThreadViewReplyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe completed!  You should not receive any more notifications for new threads in the requested forum..
        /// </summary>
        internal static string ForumUnsubscribeCompleted {
            get {
                return ResourceManager.GetString("ForumUnsubscribeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe FAILED!  An error occurred when attempting to stop notifications for new threads in a forum.  Please contact the site administrator..
        /// </summary>
        internal static string ForumUnsubscribeFailed {
            get {
                return ResourceManager.GetString("ForumUnsubscribeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Posts.
        /// </summary>
        internal static string ForumUserPostsLink {
            get {
                return ResourceManager.GetString("ForumUserPostsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} participated in these discussions..
        /// </summary>
        internal static string ForumUserThreadHeading {
            get {
                return ResourceManager.GetString("ForumUserThreadHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Thread.
        /// </summary>
        internal static string ForumViewNewThreadLabel {
            get {
                return ResourceManager.GetString("ForumViewNewThreadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Post.
        /// </summary>
        internal static string ForumViewPostLastPostLabel {
            get {
                return ResourceManager.GetString("ForumViewPostLastPostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Replies.
        /// </summary>
        internal static string ForumViewReplyCountLabel {
            get {
                return ResourceManager.GetString("ForumViewReplyCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started by.
        /// </summary>
        internal static string ForumViewStartedByLabel {
            get {
                return ResourceManager.GetString("ForumViewStartedByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string ForumViewSubjectLabel {
            get {
                return ResourceManager.GetString("ForumViewSubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This table contains a list of Forum Threads..
        /// </summary>
        internal static string ForumViewTableSummary {
            get {
                return ResourceManager.GetString("ForumViewTableSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Threads.
        /// </summary>
        internal static string ForumViewThreadCountLabel {
            get {
                return ResourceManager.GetString("ForumViewThreadCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Views.
        /// </summary>
        internal static string ForumViewViewCountLabel {
            get {
                return ResourceManager.GetString("ForumViewViewCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get your avatar.
        /// </summary>
        internal static string GravatarLinkTitle {
            get {
                return ResourceManager.GetString("GravatarLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Posting User In Notification List?.
        /// </summary>
        internal static string IncludeCurrentUserInNotifications {
            get {
                return ResourceManager.GetString("IncludeCurrentUserInNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include New Threads in Google SiteMap By Default?.
        /// </summary>
        internal static string IncludeInGoogleMap {
            get {
                return ResourceManager.GetString("IncludeInGoogleMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include In Google Site Map?.
        /// </summary>
        internal static string IncludeInSiteMap {
            get {
                return ResourceManager.GetString("IncludeInSiteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Post Body in Notification Email?.
        /// </summary>
        internal static string IncludePostBodyInNotificationEmail {
            get {
                return ResourceManager.GetString("IncludePostBodyInNotificationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Post By.
        /// </summary>
        internal static string LastPostBy {
            get {
                return ResourceManager.GetString("LastPostBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Gravatar to user profile?.
        /// </summary>
        internal static string LinkGravatarToUserProfile {
            get {
                return ResourceManager.GetString("LinkGravatarToUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        internal static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Name.
        /// </summary>
        internal static string LoginNameLabel {
            get {
                return ResourceManager.GetString("LoginNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as Answer.
        /// </summary>
        internal static string MarkAsAnswer {
            get {
                return ResourceManager.GetString("MarkAsAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as Sent.
        /// </summary>
        internal static string MarkAsSent {
            get {
                return ResourceManager.GetString("MarkAsSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderator Email Addresses (comma separated).
        /// </summary>
        internal static string ModeratorNotifyEmail {
            get {
                return ResourceManager.GetString("ModeratorNotifyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderators.
        /// </summary>
        internal static string Moderators {
            get {
                return ResourceManager.GetString("Moderators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to the feed for these forums.
        /// </summary>
        internal static string ModuleFeedLinkTooltip {
            get {
                return ResourceManager.GetString("ModuleFeedLinkTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Thread.
        /// </summary>
        internal static string NewThreadLabel {
            get {
                return ResourceManager.GetString("NewThreadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Poster &amp; Moderators.
        /// </summary>
        internal static string OriginalPosterAndModerators {
            get {
                return ResourceManager.GetString("OriginalPosterAndModerators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Notification From Address.
        /// </summary>
        internal static string OverrideNotificationFromAddress {
            get {
                return ResourceManager.GetString("OverrideNotificationFromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Notification From Alias.
        /// </summary>
        internal static string OverrideNotificationFromAlias {
            get {
                return ResourceManager.GetString("OverrideNotificationFromAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Title Override.
        /// </summary>
        internal static string PageTitleOverride {
            get {
                return ResourceManager.GetString("PageTitleOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted by {0}.
        /// </summary>
        internal static string PostedByFormat {
            get {
                return ResourceManager.GetString("PostedByFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted Links:.
        /// </summary>
        internal static string PostedLinks {
            get {
                return ResourceManager.GetString("PostedLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require Moderation Before Sending Email Notification?.
        /// </summary>
        internal static string RequireModForNotify {
            get {
                return ResourceManager.GetString("RequireModForNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles That Can Moderate.
        /// </summary>
        internal static string RolesThatCanModerate {
            get {
                return ResourceManager.GetString("RolesThatCanModerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles That Can Post.
        /// </summary>
        internal static string RolesThatCanPost {
            get {
                return ResourceManager.GetString("RolesThatCanPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include items up to this many days old in outbound feed..
        /// </summary>
        internal static string RSSFeedMaxDaysOldSetting {
            get {
                return ResourceManager.GetString("RSSFeedMaxDaysOldSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of items to include in outbound feed..
        /// </summary>
        internal static string RSSFeedMaxPostsSetting {
            get {
                return ResourceManager.GetString("RSSFeedMaxPostsSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter some text to search for..
        /// </summary>
        internal static string SearchTermRequiredWarning {
            get {
                return ResourceManager.GetString("SearchTermRequiredWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Notification To Subscribers.
        /// </summary>
        internal static string SendNotification {
            get {
                return ResourceManager.GetString("SendNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Post Notification To.
        /// </summary>
        internal static string SendPostNotificationsTo {
            get {
                return ResourceManager.GetString("SendPostNotificationsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No One.
        /// </summary>
        internal static string SendToNoOne {
            get {
                return ResourceManager.GetString("SendToNoOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Forum Search?.
        /// </summary>
        internal static string ShowForumSearchBox {
            get {
                return ResourceManager.GetString("ShowForumSearchBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Page Left Content in Forums?.
        /// </summary>
        internal static string ShowPageLeftContentSetting {
            get {
                return ResourceManager.GetString("ShowPageLeftContentSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Page Right Content in Forums?.
        /// </summary>
        internal static string ShowPageRightContentSetting {
            get {
                return ResourceManager.GetString("ShowPageRightContentSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Subscriber Count?.
        /// </summary>
        internal static string ShowSubscriberCount {
            get {
                return ResourceManager.GetString("ShowSubscriberCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticky Sort.
        /// </summary>
        internal static string StickySort {
            get {
                return ResourceManager.GetString("StickySort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        internal static string SubscribeLink {
            get {
                return ResourceManager.GetString("SubscribeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to notifications for this forum.
        /// </summary>
        internal static string SubscribeLongLink {
            get {
                return ResourceManager.GetString("SubscribeLongLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Subscribers.
        /// </summary>
        internal static string SubscriberCountFormat {
            get {
                return ResourceManager.GetString("SubscriberCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribers.
        /// </summary>
        internal static string Subscribers {
            get {
                return ResourceManager.GetString("Subscribers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribers &amp; Moderators.
        /// </summary>
        internal static string SubscribersAndModerators {
            get {
                return ResourceManager.GetString("SubscribersAndModerators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to all posts in this forum?.
        /// </summary>
        internal static string SubscribeToAllOfThisForum {
            get {
                return ResourceManager.GetString("SubscribeToAllOfThisForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppress Notification Of Post Edits?.
        /// </summary>
        internal static string SuppressNotificationOfPostEdits {
            get {
                return ResourceManager.GetString("SuppressNotificationOfPostEdits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This thread is closed to new posts..
        /// </summary>
        internal static string ThreadClosed {
            get {
                return ResourceManager.GetString("ThreadClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Page {1}.
        /// </summary>
        internal static string ThreadPageTitleFormat {
            get {
                return ResourceManager.GetString("ThreadPageTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread Subscribers.
        /// </summary>
        internal static string ThreadSubscribers {
            get {
                return ResourceManager.GetString("ThreadSubscribers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread Subscribers &amp; Moderators.
        /// </summary>
        internal static string ThreadSubscribersAndModerators {
            get {
                return ResourceManager.GetString("ThreadSubscribersAndModerators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe.
        /// </summary>
        internal static string UnsubscribeButton {
            get {
                return ResourceManager.GetString("UnsubscribeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe.
        /// </summary>
        internal static string UnSubscribeLink {
            get {
                return ResourceManager.GetString("UnSubscribeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string UserNameLabel {
            get {
                return ResourceManager.GetString("UserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View user profile for {0}.
        /// </summary>
        internal static string UserProfileLinkTooltipFormat {
            get {
                return ResourceManager.GetString("UserProfileLinkTooltipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string UserSalesLabel {
            get {
                return ResourceManager.GetString("UserSalesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site member {0} participated in these forum conversations..
        /// </summary>
        internal static string UserThreadMetaFormat {
            get {
                return ResourceManager.GetString("UserThreadMetaFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum Threads for {0}.
        /// </summary>
        internal static string UserThreadTitleFormat {
            get {
                return ResourceManager.GetString("UserThreadTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make This Forum Visble to Non Editors?.
        /// </summary>
        internal static string VisibleForum {
            get {
                return ResourceManager.GetString("VisibleForum", resourceCulture);
            }
        }
    }
}
