//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GalleryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GalleryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GalleryResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add File.
        /// </summary>
        internal static string AddFileButton {
            get {
                return ResourceManager.GetString("AddFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Gallery.
        /// </summary>
        internal static string BrowseGalleryPageTitle {
            get {
                return ResourceManager.GetString("BrowseGalleryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string BulkUploadButton {
            get {
                return ResourceManager.GetString("BulkUploadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Upload.
        /// </summary>
        internal static string BulkUploadHeading {
            get {
                return ResourceManager.GetString("BulkUploadHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Upload.
        /// </summary>
        internal static string BulkUploadLink {
            get {
                return ResourceManager.GetString("BulkUploadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        internal static string ColorBoxOpacity {
            get {
                return ResourceManager.GetString("ColorBoxOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity must be a value between 0 and 1. The default is .7.
        /// </summary>
        internal static string ColorBoxOpacityRegexWarning {
            get {
                return ResourceManager.GetString("ColorBoxOpacityRegexWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery Effects.
        /// </summary>
        internal static string ColorBoxSettings {
            get {
                return ResourceManager.GetString("ColorBoxSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Side Show on Image Click?.
        /// </summary>
        internal static string ColorBoxSlideShowAuto {
            get {
                return ResourceManager.GetString("ColorBoxSlideShowAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Show Pause Duration.
        /// </summary>
        internal static string ColorBoxSlideshowSpeed {
            get {
                return ResourceManager.GetString("ColorBoxSlideshowSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slideshow Speed must be an integer. The default is 2500.
        /// </summary>
        internal static string ColorBoxSlideshowSpeedRegexWarning {
            get {
                return ResourceManager.GetString("ColorBoxSlideshowSpeedRegexWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Slide Show Automatically?.
        /// </summary>
        internal static string ColorBoxSlideShowStartAuto {
            get {
                return ResourceManager.GetString("ColorBoxSlideShowStartAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition.
        /// </summary>
        internal static string ColorBoxTransition {
            get {
                return ResourceManager.GetString("ColorBoxTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition Speed.
        /// </summary>
        internal static string ColorBoxTransitionSpeed {
            get {
                return ResourceManager.GetString("ColorBoxTransitionSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition Speed must be an integer. The default is 350.
        /// </summary>
        internal static string ColorBoxTransitionSpeedRegexWarning {
            get {
                return ResourceManager.GetString("ColorBoxTransitionSpeedRegexWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Slide Show?.
        /// </summary>
        internal static string ColorBoxUseSlideshow {
            get {
                return ResourceManager.GetString("ColorBoxUseSlideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom CSS Class.
        /// </summary>
        internal static string CustomCssClassSetting {
            get {
                return ResourceManager.GetString("CustomCssClassSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Custom CSS Class.
        /// </summary>
        internal static string CustomCssClassSettingRegexWarning {
            get {
                return ResourceManager.GetString("CustomCssClassSettingRegexWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop an image file here or click the button to select a file (.jpg, .jpeg, .png, .gif).
        /// </summary>
        internal static string DropFile {
            get {
                return ResourceManager.GetString("DropFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop image files here or click the button to select files (.jpg, .jpeg, .png, .gif).
        /// </summary>
        internal static string DropFiles {
            get {
                return ResourceManager.GetString("DropFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery Image Editor.
        /// </summary>
        internal static string EditImagePageTitle {
            get {
                return ResourceManager.GetString("EditImagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Image.
        /// </summary>
        internal static string GalleryAddImageLabel {
            get {
                return ResourceManager.GetString("GalleryAddImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Full Size View.
        /// </summary>
        internal static string GalleryAllowFullSizeViewSetting {
            get {
                return ResourceManager.GetString("GalleryAllowFullSizeViewSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption.
        /// </summary>
        internal static string GalleryCaptionLabel {
            get {
                return ResourceManager.GetString("GalleryCaptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Image To View/Download Full Size Image.
        /// </summary>
        internal static string GalleryClickForBiggerLabel {
            get {
                return ResourceManager.GetString("GalleryClickForBiggerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact Mode (No Gallery Effects).
        /// </summary>
        internal static string GalleryCompactModeSetting {
            get {
                return ResourceManager.GetString("GalleryCompactModeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this image?.
        /// </summary>
        internal static string GalleryDeleteImageWarning {
            get {
                return ResourceManager.GetString("GalleryDeleteImageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string GalleryDescriptionLabel {
            get {
                return ResourceManager.GetString("GalleryDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        internal static string GalleryDisplayOrderLabel {
            get {
                return ResourceManager.GetString("GalleryDisplayOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string GalleryEditCancelButton {
            get {
                return ResourceManager.GetString("GalleryEditCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string GalleryEditCancelButtonAccessKey {
            get {
                return ResourceManager.GetString("GalleryEditCancelButtonAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this item.
        /// </summary>
        internal static string GalleryEditDeleteButton {
            get {
                return ResourceManager.GetString("GalleryEditDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string GalleryEditDeleteButtonAccessKey {
            get {
                return ResourceManager.GetString("GalleryEditDeleteButtonAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Settings.
        /// </summary>
        internal static string GalleryEditImageLabel {
            get {
                return ResourceManager.GetString("GalleryEditImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Image.
        /// </summary>
        internal static string GalleryEditImageLink {
            get {
                return ResourceManager.GetString("GalleryEditImageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string GalleryEditUpdateButton {
            get {
                return ResourceManager.GetString("GalleryEditUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string GalleryEditUpdateButtonAccessKey {
            get {
                return ResourceManager.GetString("GalleryEditUpdateButtonAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string GalleryFileLabel {
            get {
                return ResourceManager.GetString("GalleryFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Sub Folder Creation for Gallery.
        /// </summary>
        internal static string GalleryNotUseFoldersSetting {
            get {
                return ResourceManager.GetString("GalleryNotUseFoldersSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Selector:.
        /// </summary>
        internal static string GalleryPagerLabel {
            get {
                return ResourceManager.GetString("GalleryPagerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Technical Data.
        /// </summary>
        internal static string GalleryShowTechnicalDataSetting {
            get {
                return ResourceManager.GetString("GalleryShowTechnicalDataSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail Height.
        /// </summary>
        internal static string GalleryThumbnailHeightSetting {
            get {
                return ResourceManager.GetString("GalleryThumbnailHeightSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be an integer. The default is 75.
        /// </summary>
        internal static string GalleryThumbnailHeightSettingRegexWarning {
            get {
                return ResourceManager.GetString("GalleryThumbnailHeightSettingRegexWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnails Per Page.
        /// </summary>
        internal static string GalleryThumbnailsPerPageSetting {
            get {
                return ResourceManager.GetString("GalleryThumbnailsPerPageSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be an integer. The default is 5.
        /// </summary>
        internal static string GalleryThumbnailsPerPageSettingRegexWarning {
            get {
                return ResourceManager.GetString("GalleryThumbnailsPerPageSettingRegexWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail Width.
        /// </summary>
        internal static string GalleryThumbnailWidthSetting {
            get {
                return ResourceManager.GetString("GalleryThumbnailWidthSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be an integer. The default is 100.
        /// </summary>
        internal static string GalleryThumbnailWidthSettingRegexWarning {
            get {
                return ResourceManager.GetString("GalleryThumbnailWidthSettingRegexWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click To View/Download the original size file..
        /// </summary>
        internal static string GalleryWebImageAltText {
            get {
                return ResourceManager.GetString("GalleryWebImageAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebImage Height.
        /// </summary>
        internal static string GalleryWebImageHeightSetting {
            get {
                return ResourceManager.GetString("GalleryWebImageHeightSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be an integer. The default is 320.
        /// </summary>
        internal static string GalleryWebImageHeightSettingRegexWarning {
            get {
                return ResourceManager.GetString("GalleryWebImageHeightSettingRegexWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebImage Width.
        /// </summary>
        internal static string GalleryWebImageWidthSetting {
            get {
                return ResourceManager.GetString("GalleryWebImageWidthSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be an integer. The default is 480.
        /// </summary>
        internal static string GalleryWebImageWidthSettingRegexWarning {
            get {
                return ResourceManager.GetString("GalleryWebImageWidthSettingRegexWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more....
        /// </summary>
        internal static string GalleryWebPartMoreLink {
            get {
                return ResourceManager.GetString("GalleryWebPartMoreLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image {current} of {total}.
        /// </summary>
        internal static string ImageCountJsFormat {
            get {
                return ResourceManager.GetString("ImageCountJsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Gallery.
        /// </summary>
        internal static string ImageGalleryFeatureName {
            get {
                return ResourceManager.GetString("ImageGalleryFeatureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Galleries.
        /// </summary>
        internal static string ImageGallerySearchName {
            get {
                return ResourceManager.GetString("ImageGallerySearchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Settings.
        /// </summary>
        internal static string ImageSettings {
            get {
                return ResourceManager.GetString("ImageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file type.
        /// </summary>
        internal static string InvalidFile {
            get {
                return ResourceManager.GetString("InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} was discarded because it does not have an allowed file extension. The allowed extensions are {1}.
        /// </summary>
        internal static string InvalidUploadExtensionFormat {
            get {
                return ResourceManager.GetString("InvalidUploadExtensionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Gallery.
        /// </summary>
        internal static string LaunchGalleryLink {
            get {
                return ResourceManager.GetString("LaunchGalleryLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        internal static string MiscSettings {
            get {
                return ResourceManager.GetString("MiscSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only jpg, gif, and png files allowed..
        /// </summary>
        internal static string OnlyImageFilesAllowed {
            get {
                return ResourceManager.GetString("OnlyImageFilesAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize Background Color.
        /// </summary>
        internal static string ResizeBackgroundColor {
            get {
                return ResourceManager.GetString("ResizeBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File....
        /// </summary>
        internal static string SelectFileButton {
            get {
                return ResourceManager.GetString("SelectFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Files....
        /// </summary>
        internal static string SelectFilesButton {
            get {
                return ResourceManager.GetString("SelectFilesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silverlight Slide Show Settings - Obsolete.
        /// </summary>
        internal static string SilverlightSettings {
            get {
                return ResourceManager.GetString("SilverlightSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Show Height.
        /// </summary>
        internal static string SlideShowHeight {
            get {
                return ResourceManager.GetString("SlideShowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Show Theme.
        /// </summary>
        internal static string SlideShowTheme {
            get {
                return ResourceManager.GetString("SlideShowTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Show Width.
        /// </summary>
        internal static string SlideShowWidth {
            get {
                return ResourceManager.GetString("SlideShowWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Silverlight Windowless?.
        /// </summary>
        internal static string SlideShowWindowlessMode {
            get {
                return ResourceManager.GetString("SlideShowWindowlessMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start slideshow.
        /// </summary>
        internal static string StartSlideShow {
            get {
                return ResourceManager.GetString("StartSlideShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop slideshow.
        /// </summary>
        internal static string StopSlideShow {
            get {
                return ResourceManager.GetString("StopSlideShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Complete.
        /// </summary>
        internal static string UploadComplete {
            get {
                return ResourceManager.GetString("UploadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading....
        /// </summary>
        internal static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Nivo Slider?.
        /// </summary>
        internal static string UseNivoSlider {
            get {
                return ResourceManager.GetString("UseNivoSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Silverlight Slide Show? - Obsolete.
        /// </summary>
        internal static string UseSilverlightSlideshow {
            get {
                return ResourceManager.GetString("UseSilverlightSlideshow", resourceCulture);
            }
        }
    }
}
