//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GMapResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GMapResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GMapResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom CSS Class.
        /// </summary>
        internal static string CustomCssClassSetting {
            get {
                return ResourceManager.GetString("CustomCssClassSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Custom CSS Class.
        /// </summary>
        internal static string CustomCssClassSettingRegexWarning {
            get {
                return ResourceManager.GetString("CustomCssClassSettingRegexWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Map API Key.
        /// </summary>
        internal static string GoogleMapApiKeySetting {
            get {
                return ResourceManager.GetString("GoogleMapApiKeySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption.
        /// </summary>
        internal static string GoogleMapCaptionSetting {
            get {
                return ResourceManager.GetString("GoogleMapCaptionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string GoogleMapEditLink {
            get {
                return ResourceManager.GetString("GoogleMapEditLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Map Location and Settings.
        /// </summary>
        internal static string GoogleMapEditLinkToolTip {
            get {
                return ResourceManager.GetString("GoogleMapEditLinkToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Driving Directions.
        /// </summary>
        internal static string GoogleMapEnableDirectionsSetting {
            get {
                return ResourceManager.GetString("GoogleMapEnableDirectionsSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Local Search.
        /// </summary>
        internal static string GoogleMapEnableLocalSearchSetting {
            get {
                return ResourceManager.GetString("GoogleMapEnableLocalSearchSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Satellite and Hybrid Map Options.
        /// </summary>
        internal static string GoogleMapEnableMapTypeSetting {
            get {
                return ResourceManager.GetString("GoogleMapEnableMapTypeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Zoom Tool.
        /// </summary>
        internal static string GoogleMapEnableZoomSetting {
            get {
                return ResourceManager.GetString("GoogleMapEnableZoomSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Map.
        /// </summary>
        internal static string GoogleMapFeatureName {
            get {
                return ResourceManager.GetString("GoogleMapFeatureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Directions From.
        /// </summary>
        internal static string GoogleMapGetDirectionsFromButton {
            get {
                return ResourceManager.GetString("GoogleMapGetDirectionsFromButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get driving directions from the entered starting location..
        /// </summary>
        internal static string GoogleMapGetDirectionsFromButtonToolTip {
            get {
                return ResourceManager.GetString("GoogleMapGetDirectionsFromButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Height.
        /// </summary>
        internal static string GoogleMapHeightSetting {
            get {
                return ResourceManager.GetString("GoogleMapHeightSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Map Type.
        /// </summary>
        internal static string GoogleMapInitialMapTypeSetting {
            get {
                return ResourceManager.GetString("GoogleMapInitialMapTypeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Zoom Level.
        /// </summary>
        internal static string GoogleMapInitialZoomSetting {
            get {
                return ResourceManager.GetString("GoogleMapInitialZoomSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string GoogleMapLocationSetting {
            get {
                return ResourceManager.GetString("GoogleMapLocationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Location Info Ballon.
        /// </summary>
        internal static string GoogleMapShowInfoWindowSetting {
            get {
                return ResourceManager.GetString("GoogleMapShowInfoWindowSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Location as Caption.
        /// </summary>
        internal static string GoogleMapShowLocationCaptionSetting {
            get {
                return ResourceManager.GetString("GoogleMapShowLocationCaptionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use iframe Embed.
        /// </summary>
        internal static string GoogleMapUseIframeSetting {
            get {
                return ResourceManager.GetString("GoogleMapUseIframeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Location for Title.
        /// </summary>
        internal static string GoogleMapUseLocationForTitleSetting {
            get {
                return ResourceManager.GetString("GoogleMapUseLocationForTitleSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Width.
        /// </summary>
        internal static string GoogleMapWidthSetting {
            get {
                return ResourceManager.GetString("GoogleMapWidthSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the Google Maps API Key in Site Settings or Web.config.
        /// </summary>
        internal static string NoApiKeyWarning {
            get {
                return ResourceManager.GetString("NoApiKeyWarning", resourceCulture);
            }
        }
    }
}
