//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XmlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XmlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.XmlResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow External Images?.
        /// </summary>
        internal static string AllowExternalImages {
            get {
                return ResourceManager.GetString("AllowExternalImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom CSS Class.
        /// </summary>
        internal static string CustomCssClassSetting {
            get {
                return ResourceManager.GetString("CustomCssClassSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Custom CSS Class.
        /// </summary>
        internal static string CustomCssClassSettingRegexWarning {
            get {
                return ResourceManager.GetString("CustomCssClassSettingRegexWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop an xml or xsl file here or click the button to select a file.
        /// </summary>
        internal static string DropFile {
            get {
                return ResourceManager.GetString("DropFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string EditXmlCancelButton {
            get {
                return ResourceManager.GetString("EditXmlCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string EditXmlCancelButtonAccessKey {
            get {
                return ResourceManager.GetString("EditXmlCancelButtonAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Data File.
        /// </summary>
        internal static string EditXmlFileLabel {
            get {
                return ResourceManager.GetString("EditXmlFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose XML and XSL Files.
        /// </summary>
        internal static string EditXmlSettingsLabel {
            get {
                return ResourceManager.GetString("EditXmlSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string EditXmlUpdateButton {
            get {
                return ResourceManager.GetString("EditXmlUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string EditXmlUpdateButtonAccessKey {
            get {
                return ResourceManager.GetString("EditXmlUpdateButtonAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSL Transform File.
        /// </summary>
        internal static string EditXslFileLabel {
            get {
                return ResourceManager.GetString("EditXslFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred trying to process the Xml with Xsl. Check the error log for details or contact a site administrator..
        /// </summary>
        internal static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trust Content Completely?.
        /// </summary>
        internal static string TrustContent {
            get {
                return ResourceManager.GetString("TrustContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only .xml and .xsl files are allowed..
        /// </summary>
        internal static string UploadExtensionWarning {
            get {
                return ResourceManager.GetString("UploadExtensionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Xml or Xsl.
        /// </summary>
        internal static string UploadXmlXsl {
            get {
                return ResourceManager.GetString("UploadXmlXsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string XmlEditButton {
            get {
                return ResourceManager.GetString("XmlEditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File Selected.
        /// </summary>
        internal static string XmlNoFileSelected {
            get {
                return ResourceManager.GetString("XmlNoFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml Url.
        /// </summary>
        internal static string XmlUrl {
            get {
                return ResourceManager.GetString("XmlUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml/Xsl.
        /// </summary>
        internal static string XmlXslFeatureName {
            get {
                return ResourceManager.GetString("XmlXslFeatureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xsl Url.
        /// </summary>
        internal static string XslUrl {
            get {
                return ResourceManager.GetString("XslUrl", resourceCulture);
            }
        }
    }
}
